[project]
id      = "masm"
name    = "MASM"
version = "0.2.1"
src     = "src"
dep     = "dep"
target  = "native"
out     = "out/{target}/{profile}/bin/{name}{ext}"
obj     = "out/{target}/{profile}/obj"

[target.linux]
isa = "x86_64"
os  = "linux"
abi = "sysv64"

[bin.masm]
entry = "main.mach"

[deps.mach-std]
git = "https://github.com/octalide/mach-std"
ref = "branch/main"
